version: '3.9'

services:
  db:
    image: pgvector/pgvector:pg17
    # build:
    #   context: .
    #   dockerfile: Dockerfile.postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: admin
      POSTGRES_DB: password
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
